name: expense_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  google_fonts: ^2.1.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hexcolor: ^2.0.5
  intro_slider: ^3.0.2
  fl_chart: ^0.40.6
  shared_preferences: ^2.0.11
  syncfusion_flutter_charts: ^19.4.41

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.7

flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts:
    - family: Authenia
      fonts:
        - asset: fonts/Authenia.ttf
    - family: Brickson
      fonts:
        - asset: fonts/BricksonFree.ttf
    - family: LemonMilk
      fonts:
        - asset: fonts/LemonMilkBold.ttf
        - asset: fonts/LemonMilkLightItalic.ttf
        - asset: fonts/LemonMilkMedium.ttf
        - asset: fonts/LemonMilkMediumItalic.ttf
        - asset: fonts/LemonMilkRegular.ttf
        - asset: fonts/LemonMilkRegularItalic.ttf
    - family: Library
      fonts:
        - asset: fonts/LibraryRecordsRegular.ttf
    - family: MoongladeDemoBold
      fonts:
        - asset: fonts/MoongladeDemoBold.ttf
    - family: PotteryWheelRegular
      fonts:
        - asset: fonts/PotteryWheelRegular.ttf
    - family: StoryElementRegular
      fonts:
        - asset: fonts/StoryElementRegular.ttf
    - family: Sundaycoffee
      fonts:
        - asset: fonts/Sundaycoffee.ttf
    - family: Falco
      fonts:
        - asset: fonts/Falco_Black_Outline.ttf
          weight: 200
        - asset: fonts/FalcoBlack.ttf
          weight: 800
        - asset: fonts/Falco-Black-Inline-Negative.ttf
          weight: 400
    - family: Foundry
      fonts:
        - asset: fonts/Foundry-Font Pack.ttf
      
