name: expense_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  google_fonts: ^2.1.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hexcolor: ^2.0.5
  intro_slider: ^3.0.2
  fl_chart: ^0.40.6
  shared_preferences: ^2.0.11
  syncfusion_flutter_charts: ^19.4.41
  adaptive_theme: ^2.3.0
  month_picker_dialog: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.7

flutter:
  assets:
    - assets/
  uses-material-design: true
